export const bgScreen = '#439F8F'
export const bgHeader = '#ADADAD'
export const bgCard = '#FAFAFA'
export const colorNeutral = '#F2F2F2'
export const colorPrimary = '#19D2B1'
export const colorBlack = '#252525'